name: payplug
recipe: wordpress
config:
  webroot: wordpress
  php: 7.2
services:
  appserver:
    overrides:
      services:
        privileged: true
    run_as_root:
    - "apt-get update -y"
    - "apt-get install gnupg2 ca-certificates p11-kit chromedriver -y"
    - "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -"
    - 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list'
    - 'apt-get update -y'
    - "apt-get install google-chrome-stable -y"
  database:
    run:
    - "mysql -u root -e 'CREATE DATABASE IF NOT EXISTS wpTests;'"
    - "mysql -u root -e 'GRANT ALL PRIVILEGES ON *.* TO 'wordpress';'"
    - "mysql -u root -e 'FLUSH PRIVILEGES;'"
tooling:
  setup-tests:
    service: appserver
    cmd: "bin/setup-lando.sh"
  launch-chromedriver:
    service: appserver
    cmd: 'chromedriver --url-base=/wd/hub --headless --ignore-certificate-errors --reduce-security-for-testing --enable-features=NetworkService >/dev/null 2>&1 &'
  test-wpunit:
    service: appserver
    cmd: composer test-wpunit
    description: Run our wpunit tests
  test-acceptance:
    service: appserver
    cmd: composer test-acceptance
    description: Run our acceptance tests
  test-wpunit-all:
    service: appserver
    cmd: composer test-wpunit-all
    description: Run all the wpunit tests
  test-acceptance-all:
    service: appserver
    cmd: composer test-acceptance-all
    description: Run all the acceptance tests

events:
  # Run some commands after `lando start`
  post-start:
  - echo 'Everything installed, do not forget to launch "lando launch-chromedriver" and "lando setup-tests"'
