name: payplug
recipe: wordpress
config:
  webroot: wordpress
  php: 7.2
proxy:
  appserver:
    - payplug.localhost
tooling:
  # Runs composer install and a custom php script after your app starts
  setup-tests:
    service: appserver
    cmd: "bin/setup-lando.sh"
  launch-phantom:
    service: appserver
    cmd: 'vendor/bin/phantomjs --webdriver=4444 --ssl-protocol=any --ignore-ssl-errors=true >/dev/null 2>&1 &'
  test-wpunit:
      service: appserver
      cmd: composer test-wpunit
      description: Run our wpunit tests
  test-acceptance:
      service: appserver
      cmd: composer test-acceptance
      description: Run our acceptance tests